/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adityaalifn.learn_gradle;

public class App {
    public String getGreeting(String name) {
        return String.format("Hello, %s!", name);
    }

    public static void main(String[] args) {
        String name = "Adit";
        System.out.println(new App().getGreeting(name));
    }
}
